apps/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import success, error, login


admin.autodiscover()


urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
    url(r'^success/$', success, name='success'),
    url(r'^error/$', error, name='error'),
]

apps/core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


from .views import about, home

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # core
    url(r'^$', home, name='home'),
    url(r'^about$', about, name='about'),

    # apps
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^events/', include('events.urls', namespace='events')),

    # third party apps
    url(r'', include('facebook_auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/events/urls.py
from django.conf.urls import url

from .views import events, event_detail, ticket_detail, ticket_buy


urlpatterns = [
    url(r'^all/$', events, name='list'),
    url(r'^detail/(?P<pk>[0-9]+)$', event_detail, name='detail'),
    url(r'^ticket/(?P<pk>[0-9]+)$', ticket_detail, name='ticket'),
    url(r'^ticket/(?P<pk>[0-9]+)/buy$', ticket_buy, name='ticket_buy')
]

apps/accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth import models as auth_models


class UserEthAdress(models.Model):
    user = models.OneToOneField(auth_models.User)
    adress = models.TextField(unique=True)
    # NOTE only for demo sake we save password as text
    adress_password = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return ' '.join([self.user.email, ' | ', self.adress])

    class Meta:
        verbose_name = 'User ETH'
        verbose_name_plural = 'User ETH adresses'

apps/core/models.py
from django.db import models

# Create your models here.

apps/eth/models.py
from django.db import models

# Create your models here.

apps/events/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=255)
    starting_at = models.DateTimeField()

    def __str__(self):
        return self.title


class Ticket(models.Model):
    TICKET_TYPES = (
        # hardcoded for demo sake only
        # will be moved to separated model TicketType
        ('FAN', 'Fan Zone tickets'),
        ('VIP', 'VIP tickets')
    )

    ticket_type = models.CharField(choices=TICKET_TYPES, max_length=32)
    place = models.SmallIntegerField(null=True)
    price = models.SmallIntegerField(default=0)
    expired = models.DateTimeField()
    event = models.ForeignKey(Event, related_name='tickets', null=True, blank=True)
    available = models.BooleanField(help_text='available for sell', default=True)

    def __str__(self):
        return '{}, place {}, expired {}'.format(
            self.ticket_type, self.place, self.expired)

apps/accounts/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.messages.api import get_messages
from django.conf import settings

from facebook_auth.urls import redirect_uri

from .models import UserEthAdress


def login(request):
    # login_url = 'https://www.facebook.com/dialog/oauth?client_id={}&amp;scope={}&amp;redirect_uri={}'.format(
    #     settings.FACEBOOK_APP_ID, 'email', redirect_uri('/account/success', '/login/error')
    # )
    context = {
        'redirect_uri': redirect_uri('/account/success', '/login/error'),
        'client_id': settings.FACEBOOK_APP_ID,
        'scope': 'email'
    }
    return render_to_response('account/login.html', context)


def user_profile(request):
    pass


@login_required
def success(request):
    # Login complete view, displays user data
    ctx = {}
    return render_to_response('account/success.html', ctx, RequestContext(request))


def error(request):
    # Error view
    messages = get_messages(request)
    return render_to_response('account/error.html', {'messages': messages},
                              RequestContext(request))


def logout(request):
    # Logs out user
    auth_logout(request)
    return HttpResponseRedirect('/')

apps/core/views.py
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = 'core/home.html'


class AboutTemplateView(TemplateView):
    template_name = 'core/about.html'


about = AboutTemplateView.as_view()
home = HomeTemplateView.as_view()

apps/eth/views.py
from django.shortcuts import render

# Create your views here.

apps/events/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

from .models import Event, Ticket


class EventListView(ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'events/list.html'
    ordering = ('-pk')


class EventDetailView(DetailView):
    model = Event
    context_object_name = 'event'
    template_name = 'events/detail.html'

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        # grab all tickets associated with current event
        context['tickets'] = Ticket.objects.filter(event__id=self.object.id).order_by('place')
        return context


class TicketDetailView(DetailView):
    model = Ticket
    context_object_name = 'ticket'
    template_name = 'events/ticket.html'


def ticket_buy(request, pk):
    if request.method == 'POST':
        t = Ticket.objects.get(pk=pk)
        # TODO: send ticket to buyers adress
        t.available = False
        t.save()
        return redirect(reverse('events:ticket', kwargs={'pk': pk}))


events = EventListView.as_view()
event_detail = EventDetailView.as_view()
ticket_detail = TicketDetailView.as_view()

templates/base.html
{% load static %}

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <title>{% block title %}ETH Crypto Tickets Base{% endblock %}</title>

  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {# Global stylesheets #}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- load jquery in header, since we need it for browseid -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  {% block extra_css %}{% endblock %}
</head>
<body>

    {% include 'includes/header.html' %}

    <div class="container main-container">

    {% block content %}
    {% endblock %}

    {% include 'includes/footer.html' %}


  {# Global javascript #}
  </div>

  {% block extra_js %}{% endblock %}
</body>
</html>

templates/core/about.html
{% extends 'base.html' %}


{% block content %}

  <footer style="margin-top: 80px;">

    <div class="row">
      <div class="col-lg-12">
        <p>Developed by <a href="http://thomaspark.co">Yanik Koval</a></p>
        <p>For <a href="http://www.meetup.com/Bring-Brains-and-Blockchain-to-Ukraine-Lviv-hackathon/events/228059515/">Bring Brains and Blockchain Ukraine</a> HACKATHON</p>
        <p>Powered by <a href="http://python.org">Python</a>, <a href="http://djangoproject.com">Django</a> and
        <a href="https://www.ethereum.org/">Ethereum</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a></p>
      </div>
    </div>

  </footer>

{% endblock %}

templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="jumbotron">
    <h1>Blockchain tickets service</h1>
    <p>The most convenient way to enjoy your favorite group. Without price speculation. Paying minimum fee to re-sellers</p>
{#    <img src="{% static 'img/concert.jpg' %}" alt="">#}
    <p><a class="btn btn-success browse-events" href="{% url 'events:list' %}">Browse Events</a>
      <a class="btn btn-primary" href="{% url 'about' %}">About</a></p>
  </div>

{% endblock %}

templates/events/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      <h1>{{ event.title }}</h1>
    </div>


    <div class="col-md-6">
        <h3 class="text-info">BROOKLYN 42 at {{ event.starting_at }}</h3>

    </div>
  </div>

  {% if tickets %}

    <div class="row tickets-list">
      <div class="col-md-12">

        <ul class="tickets">

        {% for ticket in tickets %}
           <li class="col-md-1 ticket
              {{ ticket.available|yesno:'available, disabled' }}
              {% if ticket.ticket_type == 'VIP' %}ticket-vip{% endif %}">
             <a href="{% url 'events:ticket' ticket.pk %}">{{ ticket.place }}</a>
           </li>
        {% endfor %}

        </ul>

      </div>
    </div>

  {% else %}
    <div class="alert alert-dismissible alert-danger">
      <strong>Sorry!</strong> We don't have alaikable tickets for this event.
</div>
  {% endif %}

{% endblock %}

templates/events/list.html
{% extends 'base.html'  %}
{% load static %}

{% block content %}
  <div class="row">
  {% for event in events %}
      <div class="col-md-3 text-center">
        <img src="{% static 'img/250x250.png' %}" class="img-thumbnail" alt="">
        <h3>{{ event.title }}</h3>
        <p>{% lorem 22 w %}</p>
        <a href="{% url 'events:detail' event.id %}" class="btn btn-primary">Buy Tickets</a>
      </div>
  {% endfor %}
  </div>
{% endblock %}

templates/events/ticket.html
{% extends 'base.html' %}

{% block content %}
  <h2>Ticket <span class="ticket-color">{{ ticket.place }}</span> for a {{ ticket.event.title }}</h2>
  <div class="row">
    <div class="col-md-4">
      <h4>Ticket Details</h4>
      <dl class="dl-horizontal ticket-info">
        <dt>Price</dt>
        <dd>{{ ticket.price }} <i class="fa fa-eur"></i></dd>

        <dt>Ticket Type</dt>
        <dd>{{ ticket.ticket_type }}</dd>


        <dt>Place Number</dt>
        <dd>{{ ticket.place }}</dd>

        <dt>Event start</dt>
        <dd>{{ ticket.expired }}</dd>

        <dt>Available</dt>
        <dd>{{ ticket.available|yesno:"Yes, No" }}</dd>
      </dl>

      {% if ticket.available %}

        <form action="{% url 'events:ticket_buy'  ticket.id%}" method="POST" class="text-center">
          {% csrf_token %}
          <button class="btn btn-success" type="submit">
            <i class="fa fa-shopping-cart"></i> Buy This Ticket
          </button>
        </form>

      {% else %}
        <div class="alert alert-dismissible alert-danger">
          <strong>Ooops!</strong> Looks like someone already bouth this ticket.
          Brows other tickets or join waiting list.
        </div>
      {% endif %}
    </div>

    <div class="col-md-8">
      <h4>Usage Information</h4>
      {% lorem 1 p %}
      <h4>Returning The Ticket</h4>
      {% lorem 1 p %}
    </div>
  </div>
{% endblock %}

templates/includes/footer.html
<!-- moved to core/about.html, for now -->

templates/includes/header.html
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <a href="/" class="navbar-brand">Crypto <i class="fa fa-ticket"></i> Tickets</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'events:list' %}">All Concerts</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if request.user.username %}

          {# user logged in #}
          {% if request.user.email %}
            <li><a href="#"><i class="fa fa-user"></i> {{ request.user.email }}</a></li>
          {% else %}
            <li><a href="#"><i class="fa fa-user-secret"></i> {{ request.user.username }}</a></li>
            <li><a href="/admin"><i class="fa fa-cog"></i> Dashboard</a></li>
          {% endif %}

          <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out"></i> logout</a></li>

        {% else %}

          {# user not logged in #}
          <li><a href="{% url 'account:login' %}">Login as User</a></li>
          <li><a href="/admin">Login as Admin</a></li>
        {% endif %}

      </ul>

        </div>
      </div>
    </div>

templates/includes/messages.html
<ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>